#!/usr/bin/env babel-node

import faker from 'faker';
import Parse from 'parse/node';

var argv = process.argv;

if(argv.length < 3) {
  throwError('   USAGE : babel-node sample-data [COMMAND] [Additional Options]');
}

var {SERVER_URL, APP_ID} = require('../env');

Parse.initialize(APP_ID);
Parse.serverURL = `${SERVER_URL}/parse`;

var Follows = Parse.Object.extend("Follows");

var notNullValue = function(value, fakerValue) {
  return value? value: fakerValue;
}

var login = function(username, callback){

  Parse.User.logIn(username, 'password', {
    success: function(user) {
      callback(user);
    },
    error: function(user, error) {
      console.log(error);
    }
  });

}

function createUser(username, password, email, nickName, profileImage) {

  var user = new Parse.User();

  // Essential values
  user.set("username",    notNullValue(username, faker.internet.userName())); // username
  user.set("password",    notNullValue(password, "password")); // password

  // Additional values
  user.set("email",       notNullValue(email, faker.internet.email()));    // email
  user.set("nickName",    notNullValue(nickName, faker.name.findName()));     // nickName
  user.set("profileImage",notNullValue(profileImage, faker.internet.avatar()));   // profileImage

  user.signUp(null, {
    success: function(user) {
      console.log(JSON.stringify(user, null, '\t'));
    },
    error: function(user, error) {
      console.log("Error: " + error.code + " " + error.message);
    }
  });
};

// data = {keyword, pageNumber, pageSize}
function searchUsers(data) {

console.log(data);

  let limit = data.pageSize || 20; //constants.DEFAULT_PAGE_SIZE;
  let skip = ((data.pageNumber || 1) - 1) * limit;

  let usernameQuery = new Parse.Query(Parse.User);
  usernameQuery.startsWith("username", data.keyword);

  let emailQuery = new Parse.Query(Parse.User);
  emailQuery.startsWith("email", data.keyword);

  let query = Parse.Query.or(usernameQuery, emailQuery); // TODO check new ??

  if(skip > 0) query = query.skip(skip);
  query = query.limit(limit).ascending('username');

  query.find({
    success: (list) => {
      console.log(list);
    },
    error: (err) => {
      console.log(err);
    },
  });
}

function createFollow(username, follow_username){

  new Parse.Query(Parse.User)
    .equalTo("username", username)
    .first()
    .then(
      (currentUser) => {


        new Parse.Query(Parse.User)
          .equalTo("username", follow_username)
          .first()
          .then(
            (user) => {
              if(user) {
                var follow = new Follows();
                follow.set("userFrom", currentUser);
                follow.set("userTo", user);

                follow.save(null, {
                  success: function(follow) {
                    console.log(follow);
                  },
                  error: function(follow, error) {
                    console.log(error);
                  }
                });
              } else {
                console.log( params.username + ' was not existed.');
              }

            },
            (error) => { console.log(error); }
          );

        });

}

function follows(username){

    new Parse.Query(Parse.User)
      .equalTo("username", username)
      .first()
      .then(
        (currentUser) => {
          console.log(currentUser);
          new Parse.Query(Follows)
            .equalTo('userFrom', currentUser)
            .include('userTo')
            .find()
            .then(
              (list) => {
                list.map(followsParseObject);
              },
              (error) => { console.log(error); }
            );
        });

}

function followsParseObject(object){
  var user = object.get('userTo');
  console.log ({
    id: object.id,
    username: user.get('username'),
    email: user.get('email'),
  });
}

switch (argv[2]) {
  case "user:create":
    if(!argv[3]) { createUser(); } else{ createUser(argv[3]); }
    break;
  case "user:search":
    if(!argv[3]) throwError(' USAGE : babel-node sample-data user:search [keyword] ');
    searchUsers({ keyword: argv[3] });
    break;
  case "follows:create":
    if(!argv[3] || !argv[4]) throwError(' USAGE : babel-node sample-data follow:create [username] [firend\'s username]');
    createFollow(argv[3], argv[4]);
    break;
  case "follows:list":
    if(!argv[3]) throwError(' USAGE : babel-node sample-data follow:list [username] ');
    follows(argv[3]);
    break;
  default:
    console.log("Sorry, we are out of " + argv[2] + ".");
}

function throwError(msg) {
  console.info('\n', msg || 'ERROR !! ', '\n');
  process.exit(0);
}
